### PR TITLE
PHP 8 support

### LINKED ISSUE #8: Check support for PHP 8
The Travis config does not list PHP 8 as the environment to test in.

I am wondering whether this library works okay in PHP 8. We should update the tests and the config and ensure PHP 8 compatibility without dropping support for the current support PHP versions.

### PR DESCRIPTION
**Pull request by asadali214**
- Updated phpunit by added versions 8 and 9.
- Added php 8.0 to php matrix in yml file
- Fixed unit tests for phpunit 9

closes #8

### CODE REVIEW

**Comment by thehappybug** [comment]
@asadali214 I'm adding a checklist to test for before PR is merged:

* [x] Test Unirest against Tester SDK and other test SDKs in a PHP 8 environment.
* [x] Run Phan on the library to check for static analysis.

**Comment by asadali214** [comment]
@thehappybug I have completed your checklist and tested unirest against all our testing sdks in my php 8's local environment. This library is working fine with all of those

**Comment by thehappybug** [comment]
@asadali214 Were there any warnings printed to the console when you ran the tests in the SDKs?

**Comment by asadali214** [comment]
@thehappybug No there were no warnings

**Pull request merged**
