### PR TITLE
Ready for publishing

### PR DESCRIPTION
**Pull request by asadali214**
- rollback repositories in composer

### CODE REVIEW

**Comment by thehappybug** [comment]
@asadali214 It is a bad practice to have "dev-master" dependencies. Why this change?

**Comment by thehappybug** [comment]
Also, the dependency on the Git repo of apimatic-core-interfaces does not make sense. What's up?

**Comment by asadali214** [comment]
yes @thehappybug I will not be merging this PR just yet, I have added the dependency on the Git repo of apimatic-core-interfaces because its unpublished from packageist. I wanted to test it locally w/ our test SDKs hence created this commit.

I will be adding another commit as soon as we publish core-interfaces-php again after the addition of Licence file

**Review by wajahatiqbal — APPROVED** [review]
LGTM

**Pull request merged**
